### PR TITLE
CutFlow and summary plots

### PR DESCRIPTION
**Pull request by ClaudioSMV**

### CODE REVIEW

**Comment by cmadrid1** [comment]
Is this PR ready to merge? I approve of the changes.

**Comment by ClaudioSMV** [comment]
I also added the new tight edges and duplicate some 2D and 3D histograms in Analyze (those use the 'old' Loose Edges) so maybe we'll need to make sure those changes are ok.

**Comment by cmadrid1** [comment]
The code looks good. You have merge conflict now so once you fix that. I can merge this PR in.

**Comment by ClaudioSMV** [comment]
Solved! It was short. I just kept the cut you added instead of the old one in a y-position histogram!

**Comment by cmadrid1** [comment]
Great. Let me know when you are done and I'll merge it in.

**Comment by ClaudioSMV** [comment]
It's ready to go!

**Pull request merged**
